apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -gke

patches:
- patch: |-
    - op: replace
      path: /spec/destination/name
      value: gke
    - op: replace
      path: /spec/source/path
      value: app/overlays/gke
  target:
    kind: Application
