apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crc-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mlorg/gitops-tech3camp-demo.git
    targetRevision: demo
    path: cluster-config/crc
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
