apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: remove
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/selector
        value: { "matchLabels": {"type": "db"} }
    target:
      kind: StatefulSet