apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: remove
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
      - op: add
        path: /spec/volumeClaimTemplates/0/spec/selector
        value: { "matchLabels": {"type": "db"} }
    target:
      kind: StatefulSet
  - patch: |-
      - op: replace
        path: /spec/rules/0/http/paths/0/path
        value: /
    target:
      kind: Ingress
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {"name": "APP_NAV_COLOR","value": "blue"}
    target:
      kind: Deployment
