apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: remove
        path: /spec/rules/0/host
    target:
      kind: Ingress
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/storageClassName
        value: standard
    target:
      kind: StatefulSet
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value: {"name": "APP_NAV_COLOR","value": "yellow"}
    target:
      kind: Deployment