kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: petclinic
spec:
  rules:
    - host: petclinic.apps-crc.testing
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: petclinic-app
                port:
                  number: 8080
