apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service-app.yaml
  - service-db.yaml
  - ingress.yaml
  - statefulset.yaml

commonLabels:
  app: petclinic
