apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -crc

patches:
- patch: |-
    - op: replace
      path: /spec/destination/name
      value: in-cluster
    - op: replace
      path: /spec/source/path
      value: app/overlays/crc
  target:
    kind: Application
